/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gaia;  
@SuppressWarnings("all")
public class bounding_box_request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"bounding_box_request\",\"namespace\":\"avro.java.gaia\",\"fields\":[{\"name\":\"min_x\",\"type\":\"double\"},{\"name\":\"max_x\",\"type\":\"double\"},{\"name\":\"min_y\",\"type\":\"double\"},{\"name\":\"max_y\",\"type\":\"double\"},{\"name\":\"x_attr_name\",\"type\":\"string\"},{\"name\":\"y_attr_name\",\"type\":\"string\"},{\"name\":\"set_id\",\"type\":\"string\"},{\"name\":\"result_set_id\",\"type\":\"string\"},{\"name\":\"user_auth_string\",\"type\":\"string\"}]}");
  @Deprecated public double min_x;
  @Deprecated public double max_x;
  @Deprecated public double min_y;
  @Deprecated public double max_y;
  @Deprecated public java.lang.CharSequence x_attr_name;
  @Deprecated public java.lang.CharSequence y_attr_name;
  @Deprecated public java.lang.CharSequence set_id;
  @Deprecated public java.lang.CharSequence result_set_id;
  @Deprecated public java.lang.CharSequence user_auth_string;

  /**
   * Default constructor.
   */
  public bounding_box_request() {}

  /**
   * All-args constructor.
   */
  public bounding_box_request(java.lang.Double min_x, java.lang.Double max_x, java.lang.Double min_y, java.lang.Double max_y, java.lang.CharSequence x_attr_name, java.lang.CharSequence y_attr_name, java.lang.CharSequence set_id, java.lang.CharSequence result_set_id, java.lang.CharSequence user_auth_string) {
    this.min_x = min_x;
    this.max_x = max_x;
    this.min_y = min_y;
    this.max_y = max_y;
    this.x_attr_name = x_attr_name;
    this.y_attr_name = y_attr_name;
    this.set_id = set_id;
    this.result_set_id = result_set_id;
    this.user_auth_string = user_auth_string;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return min_x;
    case 1: return max_x;
    case 2: return min_y;
    case 3: return max_y;
    case 4: return x_attr_name;
    case 5: return y_attr_name;
    case 6: return set_id;
    case 7: return result_set_id;
    case 8: return user_auth_string;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: min_x = (java.lang.Double)value$; break;
    case 1: max_x = (java.lang.Double)value$; break;
    case 2: min_y = (java.lang.Double)value$; break;
    case 3: max_y = (java.lang.Double)value$; break;
    case 4: x_attr_name = (java.lang.CharSequence)value$; break;
    case 5: y_attr_name = (java.lang.CharSequence)value$; break;
    case 6: set_id = (java.lang.CharSequence)value$; break;
    case 7: result_set_id = (java.lang.CharSequence)value$; break;
    case 8: user_auth_string = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'min_x' field.
   */
  public java.lang.Double getMinX() {
    return min_x;
  }

  /**
   * Sets the value of the 'min_x' field.
   * @param value the value to set.
   */
  public void setMinX(java.lang.Double value) {
    this.min_x = value;
  }

  /**
   * Gets the value of the 'max_x' field.
   */
  public java.lang.Double getMaxX() {
    return max_x;
  }

  /**
   * Sets the value of the 'max_x' field.
   * @param value the value to set.
   */
  public void setMaxX(java.lang.Double value) {
    this.max_x = value;
  }

  /**
   * Gets the value of the 'min_y' field.
   */
  public java.lang.Double getMinY() {
    return min_y;
  }

  /**
   * Sets the value of the 'min_y' field.
   * @param value the value to set.
   */
  public void setMinY(java.lang.Double value) {
    this.min_y = value;
  }

  /**
   * Gets the value of the 'max_y' field.
   */
  public java.lang.Double getMaxY() {
    return max_y;
  }

  /**
   * Sets the value of the 'max_y' field.
   * @param value the value to set.
   */
  public void setMaxY(java.lang.Double value) {
    this.max_y = value;
  }

  /**
   * Gets the value of the 'x_attr_name' field.
   */
  public java.lang.CharSequence getXAttrName() {
    return x_attr_name;
  }

  /**
   * Sets the value of the 'x_attr_name' field.
   * @param value the value to set.
   */
  public void setXAttrName(java.lang.CharSequence value) {
    this.x_attr_name = value;
  }

  /**
   * Gets the value of the 'y_attr_name' field.
   */
  public java.lang.CharSequence getYAttrName() {
    return y_attr_name;
  }

  /**
   * Sets the value of the 'y_attr_name' field.
   * @param value the value to set.
   */
  public void setYAttrName(java.lang.CharSequence value) {
    this.y_attr_name = value;
  }

  /**
   * Gets the value of the 'set_id' field.
   */
  public java.lang.CharSequence getSetId() {
    return set_id;
  }

  /**
   * Sets the value of the 'set_id' field.
   * @param value the value to set.
   */
  public void setSetId(java.lang.CharSequence value) {
    this.set_id = value;
  }

  /**
   * Gets the value of the 'result_set_id' field.
   */
  public java.lang.CharSequence getResultSetId() {
    return result_set_id;
  }

  /**
   * Sets the value of the 'result_set_id' field.
   * @param value the value to set.
   */
  public void setResultSetId(java.lang.CharSequence value) {
    this.result_set_id = value;
  }

  /**
   * Gets the value of the 'user_auth_string' field.
   */
  public java.lang.CharSequence getUserAuthString() {
    return user_auth_string;
  }

  /**
   * Sets the value of the 'user_auth_string' field.
   * @param value the value to set.
   */
  public void setUserAuthString(java.lang.CharSequence value) {
    this.user_auth_string = value;
  }

  /** Creates a new bounding_box_request RecordBuilder */
  public static avro.java.gaia.bounding_box_request.Builder newBuilder() {
    return new avro.java.gaia.bounding_box_request.Builder();
  }
  
  /** Creates a new bounding_box_request RecordBuilder by copying an existing Builder */
  public static avro.java.gaia.bounding_box_request.Builder newBuilder(avro.java.gaia.bounding_box_request.Builder other) {
    return new avro.java.gaia.bounding_box_request.Builder(other);
  }
  
  /** Creates a new bounding_box_request RecordBuilder by copying an existing bounding_box_request instance */
  public static avro.java.gaia.bounding_box_request.Builder newBuilder(avro.java.gaia.bounding_box_request other) {
    return new avro.java.gaia.bounding_box_request.Builder(other);
  }
  
  /**
   * RecordBuilder for bounding_box_request instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<bounding_box_request>
    implements org.apache.avro.data.RecordBuilder<bounding_box_request> {

    private double min_x;
    private double max_x;
    private double min_y;
    private double max_y;
    private java.lang.CharSequence x_attr_name;
    private java.lang.CharSequence y_attr_name;
    private java.lang.CharSequence set_id;
    private java.lang.CharSequence result_set_id;
    private java.lang.CharSequence user_auth_string;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gaia.bounding_box_request.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gaia.bounding_box_request.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing bounding_box_request instance */
    private Builder(avro.java.gaia.bounding_box_request other) {
            super(avro.java.gaia.bounding_box_request.SCHEMA$);
      if (isValidValue(fields()[0], other.min_x)) {
        this.min_x = (java.lang.Double) data().deepCopy(fields()[0].schema(), other.min_x);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.max_x)) {
        this.max_x = (java.lang.Double) data().deepCopy(fields()[1].schema(), other.max_x);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.min_y)) {
        this.min_y = (java.lang.Double) data().deepCopy(fields()[2].schema(), other.min_y);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.max_y)) {
        this.max_y = (java.lang.Double) data().deepCopy(fields()[3].schema(), other.max_y);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.x_attr_name)) {
        this.x_attr_name = (java.lang.CharSequence) data().deepCopy(fields()[4].schema(), other.x_attr_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.y_attr_name)) {
        this.y_attr_name = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.y_attr_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.set_id)) {
        this.set_id = (java.lang.CharSequence) data().deepCopy(fields()[6].schema(), other.set_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.result_set_id)) {
        this.result_set_id = (java.lang.CharSequence) data().deepCopy(fields()[7].schema(), other.result_set_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.user_auth_string)) {
        this.user_auth_string = (java.lang.CharSequence) data().deepCopy(fields()[8].schema(), other.user_auth_string);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'min_x' field */
    public java.lang.Double getMinX() {
      return min_x;
    }
    
    /** Sets the value of the 'min_x' field */
    public avro.java.gaia.bounding_box_request.Builder setMinX(double value) {
      validate(fields()[0], value);
      this.min_x = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'min_x' field has been set */
    public boolean hasMinX() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'min_x' field */
    public avro.java.gaia.bounding_box_request.Builder clearMinX() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'max_x' field */
    public java.lang.Double getMaxX() {
      return max_x;
    }
    
    /** Sets the value of the 'max_x' field */
    public avro.java.gaia.bounding_box_request.Builder setMaxX(double value) {
      validate(fields()[1], value);
      this.max_x = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'max_x' field has been set */
    public boolean hasMaxX() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'max_x' field */
    public avro.java.gaia.bounding_box_request.Builder clearMaxX() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'min_y' field */
    public java.lang.Double getMinY() {
      return min_y;
    }
    
    /** Sets the value of the 'min_y' field */
    public avro.java.gaia.bounding_box_request.Builder setMinY(double value) {
      validate(fields()[2], value);
      this.min_y = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'min_y' field has been set */
    public boolean hasMinY() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'min_y' field */
    public avro.java.gaia.bounding_box_request.Builder clearMinY() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'max_y' field */
    public java.lang.Double getMaxY() {
      return max_y;
    }
    
    /** Sets the value of the 'max_y' field */
    public avro.java.gaia.bounding_box_request.Builder setMaxY(double value) {
      validate(fields()[3], value);
      this.max_y = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'max_y' field has been set */
    public boolean hasMaxY() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'max_y' field */
    public avro.java.gaia.bounding_box_request.Builder clearMaxY() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'x_attr_name' field */
    public java.lang.CharSequence getXAttrName() {
      return x_attr_name;
    }
    
    /** Sets the value of the 'x_attr_name' field */
    public avro.java.gaia.bounding_box_request.Builder setXAttrName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.x_attr_name = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'x_attr_name' field has been set */
    public boolean hasXAttrName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'x_attr_name' field */
    public avro.java.gaia.bounding_box_request.Builder clearXAttrName() {
      x_attr_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'y_attr_name' field */
    public java.lang.CharSequence getYAttrName() {
      return y_attr_name;
    }
    
    /** Sets the value of the 'y_attr_name' field */
    public avro.java.gaia.bounding_box_request.Builder setYAttrName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.y_attr_name = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'y_attr_name' field has been set */
    public boolean hasYAttrName() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'y_attr_name' field */
    public avro.java.gaia.bounding_box_request.Builder clearYAttrName() {
      y_attr_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'set_id' field */
    public java.lang.CharSequence getSetId() {
      return set_id;
    }
    
    /** Sets the value of the 'set_id' field */
    public avro.java.gaia.bounding_box_request.Builder setSetId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.set_id = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'set_id' field has been set */
    public boolean hasSetId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'set_id' field */
    public avro.java.gaia.bounding_box_request.Builder clearSetId() {
      set_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'result_set_id' field */
    public java.lang.CharSequence getResultSetId() {
      return result_set_id;
    }
    
    /** Sets the value of the 'result_set_id' field */
    public avro.java.gaia.bounding_box_request.Builder setResultSetId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.result_set_id = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'result_set_id' field has been set */
    public boolean hasResultSetId() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'result_set_id' field */
    public avro.java.gaia.bounding_box_request.Builder clearResultSetId() {
      result_set_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'user_auth_string' field */
    public java.lang.CharSequence getUserAuthString() {
      return user_auth_string;
    }
    
    /** Sets the value of the 'user_auth_string' field */
    public avro.java.gaia.bounding_box_request.Builder setUserAuthString(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.user_auth_string = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'user_auth_string' field has been set */
    public boolean hasUserAuthString() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'user_auth_string' field */
    public avro.java.gaia.bounding_box_request.Builder clearUserAuthString() {
      user_auth_string = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public bounding_box_request build() {
      try {
        bounding_box_request record = new bounding_box_request();
        record.min_x = fieldSetFlags()[0] ? this.min_x : (java.lang.Double) defaultValue(fields()[0]);
        record.max_x = fieldSetFlags()[1] ? this.max_x : (java.lang.Double) defaultValue(fields()[1]);
        record.min_y = fieldSetFlags()[2] ? this.min_y : (java.lang.Double) defaultValue(fields()[2]);
        record.max_y = fieldSetFlags()[3] ? this.max_y : (java.lang.Double) defaultValue(fields()[3]);
        record.x_attr_name = fieldSetFlags()[4] ? this.x_attr_name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.y_attr_name = fieldSetFlags()[5] ? this.y_attr_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.set_id = fieldSetFlags()[6] ? this.set_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.result_set_id = fieldSetFlags()[7] ? this.result_set_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.user_auth_string = fieldSetFlags()[8] ? this.user_auth_string : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
