/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gaia;  
@SuppressWarnings("all")
public class filter_then_histogram_request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"filter_then_histogram_request\",\"namespace\":\"avro.java.gaia\",\"fields\":[{\"name\":\"histogram_attribute\",\"type\":\"string\"},{\"name\":\"end\",\"type\":\"double\"},{\"name\":\"interval\",\"type\":\"long\"},{\"name\":\"set_id\",\"type\":\"string\"},{\"name\":\"start\",\"type\":\"double\"},{\"name\":\"filter_attribute\",\"type\":\"string\"},{\"name\":\"filter\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"user_auth_string\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence histogram_attribute;
  @Deprecated public double end;
  @Deprecated public long interval;
  @Deprecated public java.lang.CharSequence set_id;
  @Deprecated public double start;
  @Deprecated public java.lang.CharSequence filter_attribute;
  @Deprecated public java.util.List<java.lang.CharSequence> filter;
  @Deprecated public java.lang.CharSequence user_auth_string;

  /**
   * Default constructor.
   */
  public filter_then_histogram_request() {}

  /**
   * All-args constructor.
   */
  public filter_then_histogram_request(java.lang.CharSequence histogram_attribute, java.lang.Double end, java.lang.Long interval, java.lang.CharSequence set_id, java.lang.Double start, java.lang.CharSequence filter_attribute, java.util.List<java.lang.CharSequence> filter, java.lang.CharSequence user_auth_string) {
    this.histogram_attribute = histogram_attribute;
    this.end = end;
    this.interval = interval;
    this.set_id = set_id;
    this.start = start;
    this.filter_attribute = filter_attribute;
    this.filter = filter;
    this.user_auth_string = user_auth_string;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return histogram_attribute;
    case 1: return end;
    case 2: return interval;
    case 3: return set_id;
    case 4: return start;
    case 5: return filter_attribute;
    case 6: return filter;
    case 7: return user_auth_string;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: histogram_attribute = (java.lang.CharSequence)value$; break;
    case 1: end = (java.lang.Double)value$; break;
    case 2: interval = (java.lang.Long)value$; break;
    case 3: set_id = (java.lang.CharSequence)value$; break;
    case 4: start = (java.lang.Double)value$; break;
    case 5: filter_attribute = (java.lang.CharSequence)value$; break;
    case 6: filter = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: user_auth_string = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'histogram_attribute' field.
   */
  public java.lang.CharSequence getHistogramAttribute() {
    return histogram_attribute;
  }

  /**
   * Sets the value of the 'histogram_attribute' field.
   * @param value the value to set.
   */
  public void setHistogramAttribute(java.lang.CharSequence value) {
    this.histogram_attribute = value;
  }

  /**
   * Gets the value of the 'end' field.
   */
  public java.lang.Double getEnd() {
    return end;
  }

  /**
   * Sets the value of the 'end' field.
   * @param value the value to set.
   */
  public void setEnd(java.lang.Double value) {
    this.end = value;
  }

  /**
   * Gets the value of the 'interval' field.
   */
  public java.lang.Long getInterval() {
    return interval;
  }

  /**
   * Sets the value of the 'interval' field.
   * @param value the value to set.
   */
  public void setInterval(java.lang.Long value) {
    this.interval = value;
  }

  /**
   * Gets the value of the 'set_id' field.
   */
  public java.lang.CharSequence getSetId() {
    return set_id;
  }

  /**
   * Sets the value of the 'set_id' field.
   * @param value the value to set.
   */
  public void setSetId(java.lang.CharSequence value) {
    this.set_id = value;
  }

  /**
   * Gets the value of the 'start' field.
   */
  public java.lang.Double getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(java.lang.Double value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'filter_attribute' field.
   */
  public java.lang.CharSequence getFilterAttribute() {
    return filter_attribute;
  }

  /**
   * Sets the value of the 'filter_attribute' field.
   * @param value the value to set.
   */
  public void setFilterAttribute(java.lang.CharSequence value) {
    this.filter_attribute = value;
  }

  /**
   * Gets the value of the 'filter' field.
   */
  public java.util.List<java.lang.CharSequence> getFilter() {
    return filter;
  }

  /**
   * Sets the value of the 'filter' field.
   * @param value the value to set.
   */
  public void setFilter(java.util.List<java.lang.CharSequence> value) {
    this.filter = value;
  }

  /**
   * Gets the value of the 'user_auth_string' field.
   */
  public java.lang.CharSequence getUserAuthString() {
    return user_auth_string;
  }

  /**
   * Sets the value of the 'user_auth_string' field.
   * @param value the value to set.
   */
  public void setUserAuthString(java.lang.CharSequence value) {
    this.user_auth_string = value;
  }

  /** Creates a new filter_then_histogram_request RecordBuilder */
  public static avro.java.gaia.filter_then_histogram_request.Builder newBuilder() {
    return new avro.java.gaia.filter_then_histogram_request.Builder();
  }
  
  /** Creates a new filter_then_histogram_request RecordBuilder by copying an existing Builder */
  public static avro.java.gaia.filter_then_histogram_request.Builder newBuilder(avro.java.gaia.filter_then_histogram_request.Builder other) {
    return new avro.java.gaia.filter_then_histogram_request.Builder(other);
  }
  
  /** Creates a new filter_then_histogram_request RecordBuilder by copying an existing filter_then_histogram_request instance */
  public static avro.java.gaia.filter_then_histogram_request.Builder newBuilder(avro.java.gaia.filter_then_histogram_request other) {
    return new avro.java.gaia.filter_then_histogram_request.Builder(other);
  }
  
  /**
   * RecordBuilder for filter_then_histogram_request instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<filter_then_histogram_request>
    implements org.apache.avro.data.RecordBuilder<filter_then_histogram_request> {

    private java.lang.CharSequence histogram_attribute;
    private double end;
    private long interval;
    private java.lang.CharSequence set_id;
    private double start;
    private java.lang.CharSequence filter_attribute;
    private java.util.List<java.lang.CharSequence> filter;
    private java.lang.CharSequence user_auth_string;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gaia.filter_then_histogram_request.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gaia.filter_then_histogram_request.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing filter_then_histogram_request instance */
    private Builder(avro.java.gaia.filter_then_histogram_request other) {
            super(avro.java.gaia.filter_then_histogram_request.SCHEMA$);
      if (isValidValue(fields()[0], other.histogram_attribute)) {
        this.histogram_attribute = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.histogram_attribute);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.end)) {
        this.end = (java.lang.Double) data().deepCopy(fields()[1].schema(), other.end);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.interval)) {
        this.interval = (java.lang.Long) data().deepCopy(fields()[2].schema(), other.interval);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.set_id)) {
        this.set_id = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.set_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.start)) {
        this.start = (java.lang.Double) data().deepCopy(fields()[4].schema(), other.start);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.filter_attribute)) {
        this.filter_attribute = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.filter_attribute);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.filter)) {
        this.filter = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[6].schema(), other.filter);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.user_auth_string)) {
        this.user_auth_string = (java.lang.CharSequence) data().deepCopy(fields()[7].schema(), other.user_auth_string);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'histogram_attribute' field */
    public java.lang.CharSequence getHistogramAttribute() {
      return histogram_attribute;
    }
    
    /** Sets the value of the 'histogram_attribute' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setHistogramAttribute(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.histogram_attribute = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'histogram_attribute' field has been set */
    public boolean hasHistogramAttribute() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'histogram_attribute' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearHistogramAttribute() {
      histogram_attribute = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'end' field */
    public java.lang.Double getEnd() {
      return end;
    }
    
    /** Sets the value of the 'end' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setEnd(double value) {
      validate(fields()[1], value);
      this.end = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'end' field has been set */
    public boolean hasEnd() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'end' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearEnd() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'interval' field */
    public java.lang.Long getInterval() {
      return interval;
    }
    
    /** Sets the value of the 'interval' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setInterval(long value) {
      validate(fields()[2], value);
      this.interval = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'interval' field has been set */
    public boolean hasInterval() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'interval' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearInterval() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'set_id' field */
    public java.lang.CharSequence getSetId() {
      return set_id;
    }
    
    /** Sets the value of the 'set_id' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setSetId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.set_id = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'set_id' field has been set */
    public boolean hasSetId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'set_id' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearSetId() {
      set_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'start' field */
    public java.lang.Double getStart() {
      return start;
    }
    
    /** Sets the value of the 'start' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setStart(double value) {
      validate(fields()[4], value);
      this.start = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'start' field has been set */
    public boolean hasStart() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'start' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearStart() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'filter_attribute' field */
    public java.lang.CharSequence getFilterAttribute() {
      return filter_attribute;
    }
    
    /** Sets the value of the 'filter_attribute' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setFilterAttribute(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.filter_attribute = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'filter_attribute' field has been set */
    public boolean hasFilterAttribute() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'filter_attribute' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearFilterAttribute() {
      filter_attribute = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'filter' field */
    public java.util.List<java.lang.CharSequence> getFilter() {
      return filter;
    }
    
    /** Sets the value of the 'filter' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setFilter(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[6], value);
      this.filter = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'filter' field has been set */
    public boolean hasFilter() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'filter' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearFilter() {
      filter = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'user_auth_string' field */
    public java.lang.CharSequence getUserAuthString() {
      return user_auth_string;
    }
    
    /** Sets the value of the 'user_auth_string' field */
    public avro.java.gaia.filter_then_histogram_request.Builder setUserAuthString(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.user_auth_string = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'user_auth_string' field has been set */
    public boolean hasUserAuthString() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'user_auth_string' field */
    public avro.java.gaia.filter_then_histogram_request.Builder clearUserAuthString() {
      user_auth_string = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public filter_then_histogram_request build() {
      try {
        filter_then_histogram_request record = new filter_then_histogram_request();
        record.histogram_attribute = fieldSetFlags()[0] ? this.histogram_attribute : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.end = fieldSetFlags()[1] ? this.end : (java.lang.Double) defaultValue(fields()[1]);
        record.interval = fieldSetFlags()[2] ? this.interval : (java.lang.Long) defaultValue(fields()[2]);
        record.set_id = fieldSetFlags()[3] ? this.set_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.start = fieldSetFlags()[4] ? this.start : (java.lang.Double) defaultValue(fields()[4]);
        record.filter_attribute = fieldSetFlags()[5] ? this.filter_attribute : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.filter = fieldSetFlags()[6] ? this.filter : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[6]);
        record.user_auth_string = fieldSetFlags()[7] ? this.user_auth_string : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
