/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gaia;  
@SuppressWarnings("all")
public class get_tracks_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"get_tracks_response\",\"namespace\":\"avro.java.gaia\",\"fields\":[{\"name\":\"track_set_ids\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"track_ids\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  @Deprecated public java.util.List<java.lang.CharSequence> track_set_ids;
  @Deprecated public java.util.List<java.lang.CharSequence> track_ids;

  /**
   * Default constructor.
   */
  public get_tracks_response() {}

  /**
   * All-args constructor.
   */
  public get_tracks_response(java.util.List<java.lang.CharSequence> track_set_ids, java.util.List<java.lang.CharSequence> track_ids) {
    this.track_set_ids = track_set_ids;
    this.track_ids = track_ids;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return track_set_ids;
    case 1: return track_ids;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: track_set_ids = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: track_ids = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'track_set_ids' field.
   */
  public java.util.List<java.lang.CharSequence> getTrackSetIds() {
    return track_set_ids;
  }

  /**
   * Sets the value of the 'track_set_ids' field.
   * @param value the value to set.
   */
  public void setTrackSetIds(java.util.List<java.lang.CharSequence> value) {
    this.track_set_ids = value;
  }

  /**
   * Gets the value of the 'track_ids' field.
   */
  public java.util.List<java.lang.CharSequence> getTrackIds() {
    return track_ids;
  }

  /**
   * Sets the value of the 'track_ids' field.
   * @param value the value to set.
   */
  public void setTrackIds(java.util.List<java.lang.CharSequence> value) {
    this.track_ids = value;
  }

  /** Creates a new get_tracks_response RecordBuilder */
  public static avro.java.gaia.get_tracks_response.Builder newBuilder() {
    return new avro.java.gaia.get_tracks_response.Builder();
  }
  
  /** Creates a new get_tracks_response RecordBuilder by copying an existing Builder */
  public static avro.java.gaia.get_tracks_response.Builder newBuilder(avro.java.gaia.get_tracks_response.Builder other) {
    return new avro.java.gaia.get_tracks_response.Builder(other);
  }
  
  /** Creates a new get_tracks_response RecordBuilder by copying an existing get_tracks_response instance */
  public static avro.java.gaia.get_tracks_response.Builder newBuilder(avro.java.gaia.get_tracks_response other) {
    return new avro.java.gaia.get_tracks_response.Builder(other);
  }
  
  /**
   * RecordBuilder for get_tracks_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<get_tracks_response>
    implements org.apache.avro.data.RecordBuilder<get_tracks_response> {

    private java.util.List<java.lang.CharSequence> track_set_ids;
    private java.util.List<java.lang.CharSequence> track_ids;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gaia.get_tracks_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gaia.get_tracks_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing get_tracks_response instance */
    private Builder(avro.java.gaia.get_tracks_response other) {
            super(avro.java.gaia.get_tracks_response.SCHEMA$);
      if (isValidValue(fields()[0], other.track_set_ids)) {
        this.track_set_ids = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[0].schema(), other.track_set_ids);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.track_ids)) {
        this.track_ids = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[1].schema(), other.track_ids);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'track_set_ids' field */
    public java.util.List<java.lang.CharSequence> getTrackSetIds() {
      return track_set_ids;
    }
    
    /** Sets the value of the 'track_set_ids' field */
    public avro.java.gaia.get_tracks_response.Builder setTrackSetIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.track_set_ids = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'track_set_ids' field has been set */
    public boolean hasTrackSetIds() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'track_set_ids' field */
    public avro.java.gaia.get_tracks_response.Builder clearTrackSetIds() {
      track_set_ids = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'track_ids' field */
    public java.util.List<java.lang.CharSequence> getTrackIds() {
      return track_ids;
    }
    
    /** Sets the value of the 'track_ids' field */
    public avro.java.gaia.get_tracks_response.Builder setTrackIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.track_ids = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'track_ids' field has been set */
    public boolean hasTrackIds() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'track_ids' field */
    public avro.java.gaia.get_tracks_response.Builder clearTrackIds() {
      track_ids = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public get_tracks_response build() {
      try {
        get_tracks_response record = new get_tracks_response();
        record.track_set_ids = fieldSetFlags()[0] ? this.track_set_ids : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.track_ids = fieldSetFlags()[1] ? this.track_ids : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
