/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gaia;  
@SuppressWarnings("all")
public class register_trigger_range_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"register_trigger_range_response\",\"namespace\":\"avro.java.gaia\",\"fields\":[{\"name\":\"trigger_id\",\"type\":\"string\"},{\"name\":\"termination_trigger_id\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence trigger_id;
  @Deprecated public java.lang.CharSequence termination_trigger_id;

  /**
   * Default constructor.
   */
  public register_trigger_range_response() {}

  /**
   * All-args constructor.
   */
  public register_trigger_range_response(java.lang.CharSequence trigger_id, java.lang.CharSequence termination_trigger_id) {
    this.trigger_id = trigger_id;
    this.termination_trigger_id = termination_trigger_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return trigger_id;
    case 1: return termination_trigger_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: trigger_id = (java.lang.CharSequence)value$; break;
    case 1: termination_trigger_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'trigger_id' field.
   */
  public java.lang.CharSequence getTriggerId() {
    return trigger_id;
  }

  /**
   * Sets the value of the 'trigger_id' field.
   * @param value the value to set.
   */
  public void setTriggerId(java.lang.CharSequence value) {
    this.trigger_id = value;
  }

  /**
   * Gets the value of the 'termination_trigger_id' field.
   */
  public java.lang.CharSequence getTerminationTriggerId() {
    return termination_trigger_id;
  }

  /**
   * Sets the value of the 'termination_trigger_id' field.
   * @param value the value to set.
   */
  public void setTerminationTriggerId(java.lang.CharSequence value) {
    this.termination_trigger_id = value;
  }

  /** Creates a new register_trigger_range_response RecordBuilder */
  public static avro.java.gaia.register_trigger_range_response.Builder newBuilder() {
    return new avro.java.gaia.register_trigger_range_response.Builder();
  }
  
  /** Creates a new register_trigger_range_response RecordBuilder by copying an existing Builder */
  public static avro.java.gaia.register_trigger_range_response.Builder newBuilder(avro.java.gaia.register_trigger_range_response.Builder other) {
    return new avro.java.gaia.register_trigger_range_response.Builder(other);
  }
  
  /** Creates a new register_trigger_range_response RecordBuilder by copying an existing register_trigger_range_response instance */
  public static avro.java.gaia.register_trigger_range_response.Builder newBuilder(avro.java.gaia.register_trigger_range_response other) {
    return new avro.java.gaia.register_trigger_range_response.Builder(other);
  }
  
  /**
   * RecordBuilder for register_trigger_range_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<register_trigger_range_response>
    implements org.apache.avro.data.RecordBuilder<register_trigger_range_response> {

    private java.lang.CharSequence trigger_id;
    private java.lang.CharSequence termination_trigger_id;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gaia.register_trigger_range_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gaia.register_trigger_range_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing register_trigger_range_response instance */
    private Builder(avro.java.gaia.register_trigger_range_response other) {
            super(avro.java.gaia.register_trigger_range_response.SCHEMA$);
      if (isValidValue(fields()[0], other.trigger_id)) {
        this.trigger_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.trigger_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.termination_trigger_id)) {
        this.termination_trigger_id = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.termination_trigger_id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'trigger_id' field */
    public java.lang.CharSequence getTriggerId() {
      return trigger_id;
    }
    
    /** Sets the value of the 'trigger_id' field */
    public avro.java.gaia.register_trigger_range_response.Builder setTriggerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.trigger_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'trigger_id' field has been set */
    public boolean hasTriggerId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'trigger_id' field */
    public avro.java.gaia.register_trigger_range_response.Builder clearTriggerId() {
      trigger_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'termination_trigger_id' field */
    public java.lang.CharSequence getTerminationTriggerId() {
      return termination_trigger_id;
    }
    
    /** Sets the value of the 'termination_trigger_id' field */
    public avro.java.gaia.register_trigger_range_response.Builder setTerminationTriggerId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.termination_trigger_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'termination_trigger_id' field has been set */
    public boolean hasTerminationTriggerId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'termination_trigger_id' field */
    public avro.java.gaia.register_trigger_range_response.Builder clearTerminationTriggerId() {
      termination_trigger_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public register_trigger_range_response build() {
      try {
        register_trigger_range_response record = new register_trigger_range_response();
        record.trigger_id = fieldSetFlags()[0] ? this.trigger_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.termination_trigger_id = fieldSetFlags()[1] ? this.termination_trigger_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
