/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gaia;  
@SuppressWarnings("all")
public class shape_literal_intersection_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"shape_literal_intersection_response\",\"namespace\":\"avro.java.gaia\",\"fields\":[{\"name\":\"intersects\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence intersects;

  /**
   * Default constructor.
   */
  public shape_literal_intersection_response() {}

  /**
   * All-args constructor.
   */
  public shape_literal_intersection_response(java.lang.CharSequence intersects) {
    this.intersects = intersects;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return intersects;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: intersects = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'intersects' field.
   */
  public java.lang.CharSequence getIntersects() {
    return intersects;
  }

  /**
   * Sets the value of the 'intersects' field.
   * @param value the value to set.
   */
  public void setIntersects(java.lang.CharSequence value) {
    this.intersects = value;
  }

  /** Creates a new shape_literal_intersection_response RecordBuilder */
  public static avro.java.gaia.shape_literal_intersection_response.Builder newBuilder() {
    return new avro.java.gaia.shape_literal_intersection_response.Builder();
  }
  
  /** Creates a new shape_literal_intersection_response RecordBuilder by copying an existing Builder */
  public static avro.java.gaia.shape_literal_intersection_response.Builder newBuilder(avro.java.gaia.shape_literal_intersection_response.Builder other) {
    return new avro.java.gaia.shape_literal_intersection_response.Builder(other);
  }
  
  /** Creates a new shape_literal_intersection_response RecordBuilder by copying an existing shape_literal_intersection_response instance */
  public static avro.java.gaia.shape_literal_intersection_response.Builder newBuilder(avro.java.gaia.shape_literal_intersection_response other) {
    return new avro.java.gaia.shape_literal_intersection_response.Builder(other);
  }
  
  /**
   * RecordBuilder for shape_literal_intersection_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<shape_literal_intersection_response>
    implements org.apache.avro.data.RecordBuilder<shape_literal_intersection_response> {

    private java.lang.CharSequence intersects;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gaia.shape_literal_intersection_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gaia.shape_literal_intersection_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing shape_literal_intersection_response instance */
    private Builder(avro.java.gaia.shape_literal_intersection_response other) {
            super(avro.java.gaia.shape_literal_intersection_response.SCHEMA$);
      if (isValidValue(fields()[0], other.intersects)) {
        this.intersects = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.intersects);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'intersects' field */
    public java.lang.CharSequence getIntersects() {
      return intersects;
    }
    
    /** Sets the value of the 'intersects' field */
    public avro.java.gaia.shape_literal_intersection_response.Builder setIntersects(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.intersects = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'intersects' field has been set */
    public boolean hasIntersects() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'intersects' field */
    public avro.java.gaia.shape_literal_intersection_response.Builder clearIntersects() {
      intersects = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public shape_literal_intersection_response build() {
      try {
        shape_literal_intersection_response record = new shape_literal_intersection_response();
        record.intersects = fieldSetFlags()[0] ? this.intersects : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
