/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class add_object_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"add_object_response\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"OBJECT_ID\",\"type\":\"string\"},{\"name\":\"count_inserted\",\"type\":\"int\"},{\"name\":\"count_updated\",\"type\":\"int\"}]}");
  @Deprecated public java.lang.CharSequence OBJECT_ID;
  @Deprecated public int count_inserted;
  @Deprecated public int count_updated;

  /**
   * Default constructor.
   */
  public add_object_response() {}

  /**
   * All-args constructor.
   */
  public add_object_response(java.lang.CharSequence OBJECT_ID, java.lang.Integer count_inserted, java.lang.Integer count_updated) {
    this.OBJECT_ID = OBJECT_ID;
    this.count_inserted = count_inserted;
    this.count_updated = count_updated;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return OBJECT_ID;
    case 1: return count_inserted;
    case 2: return count_updated;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: OBJECT_ID = (java.lang.CharSequence)value$; break;
    case 1: count_inserted = (java.lang.Integer)value$; break;
    case 2: count_updated = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'OBJECT_ID' field.
   */
  public java.lang.CharSequence getOBJECTID() {
    return OBJECT_ID;
  }

  /**
   * Sets the value of the 'OBJECT_ID' field.
   * @param value the value to set.
   */
  public void setOBJECTID(java.lang.CharSequence value) {
    this.OBJECT_ID = value;
  }

  /**
   * Gets the value of the 'count_inserted' field.
   */
  public java.lang.Integer getCountInserted() {
    return count_inserted;
  }

  /**
   * Sets the value of the 'count_inserted' field.
   * @param value the value to set.
   */
  public void setCountInserted(java.lang.Integer value) {
    this.count_inserted = value;
  }

  /**
   * Gets the value of the 'count_updated' field.
   */
  public java.lang.Integer getCountUpdated() {
    return count_updated;
  }

  /**
   * Sets the value of the 'count_updated' field.
   * @param value the value to set.
   */
  public void setCountUpdated(java.lang.Integer value) {
    this.count_updated = value;
  }

  /** Creates a new add_object_response RecordBuilder */
  public static avro.java.gpudb.add_object_response.Builder newBuilder() {
    return new avro.java.gpudb.add_object_response.Builder();
  }
  
  /** Creates a new add_object_response RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.add_object_response.Builder newBuilder(avro.java.gpudb.add_object_response.Builder other) {
    return new avro.java.gpudb.add_object_response.Builder(other);
  }
  
  /** Creates a new add_object_response RecordBuilder by copying an existing add_object_response instance */
  public static avro.java.gpudb.add_object_response.Builder newBuilder(avro.java.gpudb.add_object_response other) {
    return new avro.java.gpudb.add_object_response.Builder(other);
  }
  
  /**
   * RecordBuilder for add_object_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<add_object_response>
    implements org.apache.avro.data.RecordBuilder<add_object_response> {

    private java.lang.CharSequence OBJECT_ID;
    private int count_inserted;
    private int count_updated;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.add_object_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.add_object_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing add_object_response instance */
    private Builder(avro.java.gpudb.add_object_response other) {
            super(avro.java.gpudb.add_object_response.SCHEMA$);
      if (isValidValue(fields()[0], other.OBJECT_ID)) {
        this.OBJECT_ID = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.OBJECT_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count_inserted)) {
        this.count_inserted = (java.lang.Integer) data().deepCopy(fields()[1].schema(), other.count_inserted);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.count_updated)) {
        this.count_updated = (java.lang.Integer) data().deepCopy(fields()[2].schema(), other.count_updated);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'OBJECT_ID' field */
    public java.lang.CharSequence getOBJECTID() {
      return OBJECT_ID;
    }
    
    /** Sets the value of the 'OBJECT_ID' field */
    public avro.java.gpudb.add_object_response.Builder setOBJECTID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.OBJECT_ID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'OBJECT_ID' field has been set */
    public boolean hasOBJECTID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'OBJECT_ID' field */
    public avro.java.gpudb.add_object_response.Builder clearOBJECTID() {
      OBJECT_ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'count_inserted' field */
    public java.lang.Integer getCountInserted() {
      return count_inserted;
    }
    
    /** Sets the value of the 'count_inserted' field */
    public avro.java.gpudb.add_object_response.Builder setCountInserted(int value) {
      validate(fields()[1], value);
      this.count_inserted = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'count_inserted' field has been set */
    public boolean hasCountInserted() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'count_inserted' field */
    public avro.java.gpudb.add_object_response.Builder clearCountInserted() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'count_updated' field */
    public java.lang.Integer getCountUpdated() {
      return count_updated;
    }
    
    /** Sets the value of the 'count_updated' field */
    public avro.java.gpudb.add_object_response.Builder setCountUpdated(int value) {
      validate(fields()[2], value);
      this.count_updated = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'count_updated' field has been set */
    public boolean hasCountUpdated() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'count_updated' field */
    public avro.java.gpudb.add_object_response.Builder clearCountUpdated() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public add_object_response build() {
      try {
        add_object_response record = new add_object_response();
        record.OBJECT_ID = fieldSetFlags()[0] ? this.OBJECT_ID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.count_inserted = fieldSetFlags()[1] ? this.count_inserted : (java.lang.Integer) defaultValue(fields()[1]);
        record.count_updated = fieldSetFlags()[2] ? this.count_updated : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
