/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class authenticate_users_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"authenticate_users_response\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"user_auth_strings\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"set_ids\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  @Deprecated public java.util.List<java.lang.CharSequence> user_auth_strings;
  @Deprecated public java.util.List<java.lang.CharSequence> set_ids;

  /**
   * Default constructor.
   */
  public authenticate_users_response() {}

  /**
   * All-args constructor.
   */
  public authenticate_users_response(java.util.List<java.lang.CharSequence> user_auth_strings, java.util.List<java.lang.CharSequence> set_ids) {
    this.user_auth_strings = user_auth_strings;
    this.set_ids = set_ids;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_auth_strings;
    case 1: return set_ids;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_auth_strings = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: set_ids = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'user_auth_strings' field.
   */
  public java.util.List<java.lang.CharSequence> getUserAuthStrings() {
    return user_auth_strings;
  }

  /**
   * Sets the value of the 'user_auth_strings' field.
   * @param value the value to set.
   */
  public void setUserAuthStrings(java.util.List<java.lang.CharSequence> value) {
    this.user_auth_strings = value;
  }

  /**
   * Gets the value of the 'set_ids' field.
   */
  public java.util.List<java.lang.CharSequence> getSetIds() {
    return set_ids;
  }

  /**
   * Sets the value of the 'set_ids' field.
   * @param value the value to set.
   */
  public void setSetIds(java.util.List<java.lang.CharSequence> value) {
    this.set_ids = value;
  }

  /** Creates a new authenticate_users_response RecordBuilder */
  public static avro.java.gpudb.authenticate_users_response.Builder newBuilder() {
    return new avro.java.gpudb.authenticate_users_response.Builder();
  }
  
  /** Creates a new authenticate_users_response RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.authenticate_users_response.Builder newBuilder(avro.java.gpudb.authenticate_users_response.Builder other) {
    return new avro.java.gpudb.authenticate_users_response.Builder(other);
  }
  
  /** Creates a new authenticate_users_response RecordBuilder by copying an existing authenticate_users_response instance */
  public static avro.java.gpudb.authenticate_users_response.Builder newBuilder(avro.java.gpudb.authenticate_users_response other) {
    return new avro.java.gpudb.authenticate_users_response.Builder(other);
  }
  
  /**
   * RecordBuilder for authenticate_users_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<authenticate_users_response>
    implements org.apache.avro.data.RecordBuilder<authenticate_users_response> {

    private java.util.List<java.lang.CharSequence> user_auth_strings;
    private java.util.List<java.lang.CharSequence> set_ids;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.authenticate_users_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.authenticate_users_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing authenticate_users_response instance */
    private Builder(avro.java.gpudb.authenticate_users_response other) {
            super(avro.java.gpudb.authenticate_users_response.SCHEMA$);
      if (isValidValue(fields()[0], other.user_auth_strings)) {
        this.user_auth_strings = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[0].schema(), other.user_auth_strings);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.set_ids)) {
        this.set_ids = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[1].schema(), other.set_ids);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'user_auth_strings' field */
    public java.util.List<java.lang.CharSequence> getUserAuthStrings() {
      return user_auth_strings;
    }
    
    /** Sets the value of the 'user_auth_strings' field */
    public avro.java.gpudb.authenticate_users_response.Builder setUserAuthStrings(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.user_auth_strings = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'user_auth_strings' field has been set */
    public boolean hasUserAuthStrings() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'user_auth_strings' field */
    public avro.java.gpudb.authenticate_users_response.Builder clearUserAuthStrings() {
      user_auth_strings = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'set_ids' field */
    public java.util.List<java.lang.CharSequence> getSetIds() {
      return set_ids;
    }
    
    /** Sets the value of the 'set_ids' field */
    public avro.java.gpudb.authenticate_users_response.Builder setSetIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.set_ids = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'set_ids' field has been set */
    public boolean hasSetIds() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'set_ids' field */
    public avro.java.gpudb.authenticate_users_response.Builder clearSetIds() {
      set_ids = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public authenticate_users_response build() {
      try {
        authenticate_users_response record = new authenticate_users_response();
        record.user_auth_strings = fieldSetFlags()[0] ? this.user_auth_strings : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.set_ids = fieldSetFlags()[1] ? this.set_ids : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
