/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class convex_hull_request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"convex_hull_request\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"x_attr_name\",\"type\":\"string\"},{\"name\":\"y_attr_name\",\"type\":\"string\"},{\"name\":\"set_id\",\"type\":\"string\"},{\"name\":\"user_auth_string\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence x_attr_name;
  @Deprecated public java.lang.CharSequence y_attr_name;
  @Deprecated public java.lang.CharSequence set_id;
  @Deprecated public java.lang.CharSequence user_auth_string;

  /**
   * Default constructor.
   */
  public convex_hull_request() {}

  /**
   * All-args constructor.
   */
  public convex_hull_request(java.lang.CharSequence x_attr_name, java.lang.CharSequence y_attr_name, java.lang.CharSequence set_id, java.lang.CharSequence user_auth_string) {
    this.x_attr_name = x_attr_name;
    this.y_attr_name = y_attr_name;
    this.set_id = set_id;
    this.user_auth_string = user_auth_string;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return x_attr_name;
    case 1: return y_attr_name;
    case 2: return set_id;
    case 3: return user_auth_string;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: x_attr_name = (java.lang.CharSequence)value$; break;
    case 1: y_attr_name = (java.lang.CharSequence)value$; break;
    case 2: set_id = (java.lang.CharSequence)value$; break;
    case 3: user_auth_string = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'x_attr_name' field.
   */
  public java.lang.CharSequence getXAttrName() {
    return x_attr_name;
  }

  /**
   * Sets the value of the 'x_attr_name' field.
   * @param value the value to set.
   */
  public void setXAttrName(java.lang.CharSequence value) {
    this.x_attr_name = value;
  }

  /**
   * Gets the value of the 'y_attr_name' field.
   */
  public java.lang.CharSequence getYAttrName() {
    return y_attr_name;
  }

  /**
   * Sets the value of the 'y_attr_name' field.
   * @param value the value to set.
   */
  public void setYAttrName(java.lang.CharSequence value) {
    this.y_attr_name = value;
  }

  /**
   * Gets the value of the 'set_id' field.
   */
  public java.lang.CharSequence getSetId() {
    return set_id;
  }

  /**
   * Sets the value of the 'set_id' field.
   * @param value the value to set.
   */
  public void setSetId(java.lang.CharSequence value) {
    this.set_id = value;
  }

  /**
   * Gets the value of the 'user_auth_string' field.
   */
  public java.lang.CharSequence getUserAuthString() {
    return user_auth_string;
  }

  /**
   * Sets the value of the 'user_auth_string' field.
   * @param value the value to set.
   */
  public void setUserAuthString(java.lang.CharSequence value) {
    this.user_auth_string = value;
  }

  /** Creates a new convex_hull_request RecordBuilder */
  public static avro.java.gpudb.convex_hull_request.Builder newBuilder() {
    return new avro.java.gpudb.convex_hull_request.Builder();
  }
  
  /** Creates a new convex_hull_request RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.convex_hull_request.Builder newBuilder(avro.java.gpudb.convex_hull_request.Builder other) {
    return new avro.java.gpudb.convex_hull_request.Builder(other);
  }
  
  /** Creates a new convex_hull_request RecordBuilder by copying an existing convex_hull_request instance */
  public static avro.java.gpudb.convex_hull_request.Builder newBuilder(avro.java.gpudb.convex_hull_request other) {
    return new avro.java.gpudb.convex_hull_request.Builder(other);
  }
  
  /**
   * RecordBuilder for convex_hull_request instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<convex_hull_request>
    implements org.apache.avro.data.RecordBuilder<convex_hull_request> {

    private java.lang.CharSequence x_attr_name;
    private java.lang.CharSequence y_attr_name;
    private java.lang.CharSequence set_id;
    private java.lang.CharSequence user_auth_string;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.convex_hull_request.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.convex_hull_request.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing convex_hull_request instance */
    private Builder(avro.java.gpudb.convex_hull_request other) {
            super(avro.java.gpudb.convex_hull_request.SCHEMA$);
      if (isValidValue(fields()[0], other.x_attr_name)) {
        this.x_attr_name = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.x_attr_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.y_attr_name)) {
        this.y_attr_name = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.y_attr_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.set_id)) {
        this.set_id = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.set_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.user_auth_string)) {
        this.user_auth_string = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.user_auth_string);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'x_attr_name' field */
    public java.lang.CharSequence getXAttrName() {
      return x_attr_name;
    }
    
    /** Sets the value of the 'x_attr_name' field */
    public avro.java.gpudb.convex_hull_request.Builder setXAttrName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.x_attr_name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'x_attr_name' field has been set */
    public boolean hasXAttrName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'x_attr_name' field */
    public avro.java.gpudb.convex_hull_request.Builder clearXAttrName() {
      x_attr_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'y_attr_name' field */
    public java.lang.CharSequence getYAttrName() {
      return y_attr_name;
    }
    
    /** Sets the value of the 'y_attr_name' field */
    public avro.java.gpudb.convex_hull_request.Builder setYAttrName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.y_attr_name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'y_attr_name' field has been set */
    public boolean hasYAttrName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'y_attr_name' field */
    public avro.java.gpudb.convex_hull_request.Builder clearYAttrName() {
      y_attr_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'set_id' field */
    public java.lang.CharSequence getSetId() {
      return set_id;
    }
    
    /** Sets the value of the 'set_id' field */
    public avro.java.gpudb.convex_hull_request.Builder setSetId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.set_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'set_id' field has been set */
    public boolean hasSetId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'set_id' field */
    public avro.java.gpudb.convex_hull_request.Builder clearSetId() {
      set_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'user_auth_string' field */
    public java.lang.CharSequence getUserAuthString() {
      return user_auth_string;
    }
    
    /** Sets the value of the 'user_auth_string' field */
    public avro.java.gpudb.convex_hull_request.Builder setUserAuthString(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.user_auth_string = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'user_auth_string' field has been set */
    public boolean hasUserAuthString() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'user_auth_string' field */
    public avro.java.gpudb.convex_hull_request.Builder clearUserAuthString() {
      user_auth_string = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public convex_hull_request build() {
      try {
        convex_hull_request record = new convex_hull_request();
        record.x_attr_name = fieldSetFlags()[0] ? this.x_attr_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.y_attr_name = fieldSetFlags()[1] ? this.y_attr_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.set_id = fieldSetFlags()[2] ? this.set_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.user_auth_string = fieldSetFlags()[3] ? this.user_auth_string : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
