/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class get_values_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"get_values_response\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"int_attrs\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"int\"}}},{\"name\":\"long_attrs\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"long\"}}},{\"name\":\"float_attrs\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"float\"}}},{\"name\":\"double_attrs\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"double\"}}},{\"name\":\"string_attrs\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"string\"}}},{\"name\":\"set_id\",\"type\":\"string\"}]}");
  @Deprecated public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> int_attrs;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>> long_attrs;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>> float_attrs;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>> double_attrs;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> string_attrs;
  @Deprecated public java.lang.CharSequence set_id;

  /**
   * Default constructor.
   */
  public get_values_response() {}

  /**
   * All-args constructor.
   */
  public get_values_response(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> int_attrs, java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>> long_attrs, java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>> float_attrs, java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>> double_attrs, java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> string_attrs, java.lang.CharSequence set_id) {
    this.int_attrs = int_attrs;
    this.long_attrs = long_attrs;
    this.float_attrs = float_attrs;
    this.double_attrs = double_attrs;
    this.string_attrs = string_attrs;
    this.set_id = set_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return int_attrs;
    case 1: return long_attrs;
    case 2: return float_attrs;
    case 3: return double_attrs;
    case 4: return string_attrs;
    case 5: return set_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: int_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>>)value$; break;
    case 1: long_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>>)value$; break;
    case 2: float_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>>)value$; break;
    case 3: double_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>>)value$; break;
    case 4: string_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>)value$; break;
    case 5: set_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'int_attrs' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> getIntAttrs() {
    return int_attrs;
  }

  /**
   * Sets the value of the 'int_attrs' field.
   * @param value the value to set.
   */
  public void setIntAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> value) {
    this.int_attrs = value;
  }

  /**
   * Gets the value of the 'long_attrs' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>> getLongAttrs() {
    return long_attrs;
  }

  /**
   * Sets the value of the 'long_attrs' field.
   * @param value the value to set.
   */
  public void setLongAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>> value) {
    this.long_attrs = value;
  }

  /**
   * Gets the value of the 'float_attrs' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>> getFloatAttrs() {
    return float_attrs;
  }

  /**
   * Sets the value of the 'float_attrs' field.
   * @param value the value to set.
   */
  public void setFloatAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>> value) {
    this.float_attrs = value;
  }

  /**
   * Gets the value of the 'double_attrs' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>> getDoubleAttrs() {
    return double_attrs;
  }

  /**
   * Sets the value of the 'double_attrs' field.
   * @param value the value to set.
   */
  public void setDoubleAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>> value) {
    this.double_attrs = value;
  }

  /**
   * Gets the value of the 'string_attrs' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> getStringAttrs() {
    return string_attrs;
  }

  /**
   * Sets the value of the 'string_attrs' field.
   * @param value the value to set.
   */
  public void setStringAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> value) {
    this.string_attrs = value;
  }

  /**
   * Gets the value of the 'set_id' field.
   */
  public java.lang.CharSequence getSetId() {
    return set_id;
  }

  /**
   * Sets the value of the 'set_id' field.
   * @param value the value to set.
   */
  public void setSetId(java.lang.CharSequence value) {
    this.set_id = value;
  }

  /** Creates a new get_values_response RecordBuilder */
  public static avro.java.gpudb.get_values_response.Builder newBuilder() {
    return new avro.java.gpudb.get_values_response.Builder();
  }
  
  /** Creates a new get_values_response RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.get_values_response.Builder newBuilder(avro.java.gpudb.get_values_response.Builder other) {
    return new avro.java.gpudb.get_values_response.Builder(other);
  }
  
  /** Creates a new get_values_response RecordBuilder by copying an existing get_values_response instance */
  public static avro.java.gpudb.get_values_response.Builder newBuilder(avro.java.gpudb.get_values_response other) {
    return new avro.java.gpudb.get_values_response.Builder(other);
  }
  
  /**
   * RecordBuilder for get_values_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<get_values_response>
    implements org.apache.avro.data.RecordBuilder<get_values_response> {

    private java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> int_attrs;
    private java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>> long_attrs;
    private java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>> float_attrs;
    private java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>> double_attrs;
    private java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> string_attrs;
    private java.lang.CharSequence set_id;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.get_values_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.get_values_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing get_values_response instance */
    private Builder(avro.java.gpudb.get_values_response other) {
            super(avro.java.gpudb.get_values_response.SCHEMA$);
      if (isValidValue(fields()[0], other.int_attrs)) {
        this.int_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>>) data().deepCopy(fields()[0].schema(), other.int_attrs);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.long_attrs)) {
        this.long_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>>) data().deepCopy(fields()[1].schema(), other.long_attrs);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.float_attrs)) {
        this.float_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>>) data().deepCopy(fields()[2].schema(), other.float_attrs);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.double_attrs)) {
        this.double_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>>) data().deepCopy(fields()[3].schema(), other.double_attrs);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.string_attrs)) {
        this.string_attrs = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>) data().deepCopy(fields()[4].schema(), other.string_attrs);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.set_id)) {
        this.set_id = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.set_id);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'int_attrs' field */
    public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> getIntAttrs() {
      return int_attrs;
    }
    
    /** Sets the value of the 'int_attrs' field */
    public avro.java.gpudb.get_values_response.Builder setIntAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> value) {
      validate(fields()[0], value);
      this.int_attrs = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'int_attrs' field has been set */
    public boolean hasIntAttrs() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'int_attrs' field */
    public avro.java.gpudb.get_values_response.Builder clearIntAttrs() {
      int_attrs = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'long_attrs' field */
    public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>> getLongAttrs() {
      return long_attrs;
    }
    
    /** Sets the value of the 'long_attrs' field */
    public avro.java.gpudb.get_values_response.Builder setLongAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>> value) {
      validate(fields()[1], value);
      this.long_attrs = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'long_attrs' field has been set */
    public boolean hasLongAttrs() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'long_attrs' field */
    public avro.java.gpudb.get_values_response.Builder clearLongAttrs() {
      long_attrs = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'float_attrs' field */
    public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>> getFloatAttrs() {
      return float_attrs;
    }
    
    /** Sets the value of the 'float_attrs' field */
    public avro.java.gpudb.get_values_response.Builder setFloatAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>> value) {
      validate(fields()[2], value);
      this.float_attrs = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'float_attrs' field has been set */
    public boolean hasFloatAttrs() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'float_attrs' field */
    public avro.java.gpudb.get_values_response.Builder clearFloatAttrs() {
      float_attrs = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'double_attrs' field */
    public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>> getDoubleAttrs() {
      return double_attrs;
    }
    
    /** Sets the value of the 'double_attrs' field */
    public avro.java.gpudb.get_values_response.Builder setDoubleAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>> value) {
      validate(fields()[3], value);
      this.double_attrs = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'double_attrs' field has been set */
    public boolean hasDoubleAttrs() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'double_attrs' field */
    public avro.java.gpudb.get_values_response.Builder clearDoubleAttrs() {
      double_attrs = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'string_attrs' field */
    public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> getStringAttrs() {
      return string_attrs;
    }
    
    /** Sets the value of the 'string_attrs' field */
    public avro.java.gpudb.get_values_response.Builder setStringAttrs(java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> value) {
      validate(fields()[4], value);
      this.string_attrs = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'string_attrs' field has been set */
    public boolean hasStringAttrs() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'string_attrs' field */
    public avro.java.gpudb.get_values_response.Builder clearStringAttrs() {
      string_attrs = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'set_id' field */
    public java.lang.CharSequence getSetId() {
      return set_id;
    }
    
    /** Sets the value of the 'set_id' field */
    public avro.java.gpudb.get_values_response.Builder setSetId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.set_id = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'set_id' field has been set */
    public boolean hasSetId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'set_id' field */
    public avro.java.gpudb.get_values_response.Builder clearSetId() {
      set_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public get_values_response build() {
      try {
        get_values_response record = new get_values_response();
        record.int_attrs = fieldSetFlags()[0] ? this.int_attrs : (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>>) defaultValue(fields()[0]);
        record.long_attrs = fieldSetFlags()[1] ? this.long_attrs : (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Long>>) defaultValue(fields()[1]);
        record.float_attrs = fieldSetFlags()[2] ? this.float_attrs : (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Float>>) defaultValue(fields()[2]);
        record.double_attrs = fieldSetFlags()[3] ? this.double_attrs : (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Double>>) defaultValue(fields()[3]);
        record.string_attrs = fieldSetFlags()[4] ? this.string_attrs : (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>) defaultValue(fields()[4]);
        record.set_id = fieldSetFlags()[5] ? this.set_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
