/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class random_request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"random_request\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"set_id\",\"type\":\"string\"},{\"name\":\"count\",\"type\":\"long\"},{\"name\":\"param_map\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"map\",\"values\":\"double\"}}}]}");
  @Deprecated public java.lang.CharSequence set_id;
  @Deprecated public long count;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>> param_map;

  /**
   * Default constructor.
   */
  public random_request() {}

  /**
   * All-args constructor.
   */
  public random_request(java.lang.CharSequence set_id, java.lang.Long count, java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>> param_map) {
    this.set_id = set_id;
    this.count = count;
    this.param_map = param_map;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return set_id;
    case 1: return count;
    case 2: return param_map;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: set_id = (java.lang.CharSequence)value$; break;
    case 1: count = (java.lang.Long)value$; break;
    case 2: param_map = (java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'set_id' field.
   */
  public java.lang.CharSequence getSetId() {
    return set_id;
  }

  /**
   * Sets the value of the 'set_id' field.
   * @param value the value to set.
   */
  public void setSetId(java.lang.CharSequence value) {
    this.set_id = value;
  }

  /**
   * Gets the value of the 'count' field.
   */
  public java.lang.Long getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Long value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'param_map' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>> getParamMap() {
    return param_map;
  }

  /**
   * Sets the value of the 'param_map' field.
   * @param value the value to set.
   */
  public void setParamMap(java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>> value) {
    this.param_map = value;
  }

  /** Creates a new random_request RecordBuilder */
  public static avro.java.gpudb.random_request.Builder newBuilder() {
    return new avro.java.gpudb.random_request.Builder();
  }
  
  /** Creates a new random_request RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.random_request.Builder newBuilder(avro.java.gpudb.random_request.Builder other) {
    return new avro.java.gpudb.random_request.Builder(other);
  }
  
  /** Creates a new random_request RecordBuilder by copying an existing random_request instance */
  public static avro.java.gpudb.random_request.Builder newBuilder(avro.java.gpudb.random_request other) {
    return new avro.java.gpudb.random_request.Builder(other);
  }
  
  /**
   * RecordBuilder for random_request instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<random_request>
    implements org.apache.avro.data.RecordBuilder<random_request> {

    private java.lang.CharSequence set_id;
    private long count;
    private java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>> param_map;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.random_request.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.random_request.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing random_request instance */
    private Builder(avro.java.gpudb.random_request other) {
            super(avro.java.gpudb.random_request.SCHEMA$);
      if (isValidValue(fields()[0], other.set_id)) {
        this.set_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.set_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count)) {
        this.count = (java.lang.Long) data().deepCopy(fields()[1].schema(), other.count);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.param_map)) {
        this.param_map = (java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>>) data().deepCopy(fields()[2].schema(), other.param_map);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'set_id' field */
    public java.lang.CharSequence getSetId() {
      return set_id;
    }
    
    /** Sets the value of the 'set_id' field */
    public avro.java.gpudb.random_request.Builder setSetId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.set_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'set_id' field has been set */
    public boolean hasSetId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'set_id' field */
    public avro.java.gpudb.random_request.Builder clearSetId() {
      set_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'count' field */
    public java.lang.Long getCount() {
      return count;
    }
    
    /** Sets the value of the 'count' field */
    public avro.java.gpudb.random_request.Builder setCount(long value) {
      validate(fields()[1], value);
      this.count = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'count' field has been set */
    public boolean hasCount() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'count' field */
    public avro.java.gpudb.random_request.Builder clearCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'param_map' field */
    public java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>> getParamMap() {
      return param_map;
    }
    
    /** Sets the value of the 'param_map' field */
    public avro.java.gpudb.random_request.Builder setParamMap(java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>> value) {
      validate(fields()[2], value);
      this.param_map = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'param_map' field has been set */
    public boolean hasParamMap() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'param_map' field */
    public avro.java.gpudb.random_request.Builder clearParamMap() {
      param_map = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public random_request build() {
      try {
        random_request record = new random_request();
        record.set_id = fieldSetFlags()[0] ? this.set_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.count = fieldSetFlags()[1] ? this.count : (java.lang.Long) defaultValue(fields()[1]);
        record.param_map = fieldSetFlags()[2] ? this.param_map : (java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,java.lang.Double>>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
