/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class register_type_transform_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"register_type_transform_response\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"type_id\",\"type\":\"string\"},{\"name\":\"new_type_id\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence type_id;
  @Deprecated public java.lang.CharSequence new_type_id;

  /**
   * Default constructor.
   */
  public register_type_transform_response() {}

  /**
   * All-args constructor.
   */
  public register_type_transform_response(java.lang.CharSequence type_id, java.lang.CharSequence new_type_id) {
    this.type_id = type_id;
    this.new_type_id = new_type_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type_id;
    case 1: return new_type_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type_id = (java.lang.CharSequence)value$; break;
    case 1: new_type_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type_id' field.
   */
  public java.lang.CharSequence getTypeId() {
    return type_id;
  }

  /**
   * Sets the value of the 'type_id' field.
   * @param value the value to set.
   */
  public void setTypeId(java.lang.CharSequence value) {
    this.type_id = value;
  }

  /**
   * Gets the value of the 'new_type_id' field.
   */
  public java.lang.CharSequence getNewTypeId() {
    return new_type_id;
  }

  /**
   * Sets the value of the 'new_type_id' field.
   * @param value the value to set.
   */
  public void setNewTypeId(java.lang.CharSequence value) {
    this.new_type_id = value;
  }

  /** Creates a new register_type_transform_response RecordBuilder */
  public static avro.java.gpudb.register_type_transform_response.Builder newBuilder() {
    return new avro.java.gpudb.register_type_transform_response.Builder();
  }
  
  /** Creates a new register_type_transform_response RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.register_type_transform_response.Builder newBuilder(avro.java.gpudb.register_type_transform_response.Builder other) {
    return new avro.java.gpudb.register_type_transform_response.Builder(other);
  }
  
  /** Creates a new register_type_transform_response RecordBuilder by copying an existing register_type_transform_response instance */
  public static avro.java.gpudb.register_type_transform_response.Builder newBuilder(avro.java.gpudb.register_type_transform_response other) {
    return new avro.java.gpudb.register_type_transform_response.Builder(other);
  }
  
  /**
   * RecordBuilder for register_type_transform_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<register_type_transform_response>
    implements org.apache.avro.data.RecordBuilder<register_type_transform_response> {

    private java.lang.CharSequence type_id;
    private java.lang.CharSequence new_type_id;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.register_type_transform_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.register_type_transform_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing register_type_transform_response instance */
    private Builder(avro.java.gpudb.register_type_transform_response other) {
            super(avro.java.gpudb.register_type_transform_response.SCHEMA$);
      if (isValidValue(fields()[0], other.type_id)) {
        this.type_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.type_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.new_type_id)) {
        this.new_type_id = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.new_type_id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'type_id' field */
    public java.lang.CharSequence getTypeId() {
      return type_id;
    }
    
    /** Sets the value of the 'type_id' field */
    public avro.java.gpudb.register_type_transform_response.Builder setTypeId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.type_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'type_id' field has been set */
    public boolean hasTypeId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'type_id' field */
    public avro.java.gpudb.register_type_transform_response.Builder clearTypeId() {
      type_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'new_type_id' field */
    public java.lang.CharSequence getNewTypeId() {
      return new_type_id;
    }
    
    /** Sets the value of the 'new_type_id' field */
    public avro.java.gpudb.register_type_transform_response.Builder setNewTypeId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.new_type_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'new_type_id' field has been set */
    public boolean hasNewTypeId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'new_type_id' field */
    public avro.java.gpudb.register_type_transform_response.Builder clearNewTypeId() {
      new_type_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public register_type_transform_response build() {
      try {
        register_type_transform_response record = new register_type_transform_response();
        record.type_id = fieldSetFlags()[0] ? this.type_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.new_type_id = fieldSetFlags()[1] ? this.new_type_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
