/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class register_parent_set_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"register_parent_set_response\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"set_id\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence set_id;

  /**
   * Default constructor.
   */
  public register_parent_set_response() {}

  /**
   * All-args constructor.
   */
  public register_parent_set_response(java.lang.CharSequence set_id) {
    this.set_id = set_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return set_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: set_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'set_id' field.
   */
  public java.lang.CharSequence getSetId() {
    return set_id;
  }

  /**
   * Sets the value of the 'set_id' field.
   * @param value the value to set.
   */
  public void setSetId(java.lang.CharSequence value) {
    this.set_id = value;
  }

  /** Creates a new register_parent_set_response RecordBuilder */
  public static avro.java.gpudb.register_parent_set_response.Builder newBuilder() {
    return new avro.java.gpudb.register_parent_set_response.Builder();
  }
  
  /** Creates a new register_parent_set_response RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.register_parent_set_response.Builder newBuilder(avro.java.gpudb.register_parent_set_response.Builder other) {
    return new avro.java.gpudb.register_parent_set_response.Builder(other);
  }
  
  /** Creates a new register_parent_set_response RecordBuilder by copying an existing register_parent_set_response instance */
  public static avro.java.gpudb.register_parent_set_response.Builder newBuilder(avro.java.gpudb.register_parent_set_response other) {
    return new avro.java.gpudb.register_parent_set_response.Builder(other);
  }
  
  /**
   * RecordBuilder for register_parent_set_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<register_parent_set_response>
    implements org.apache.avro.data.RecordBuilder<register_parent_set_response> {

    private java.lang.CharSequence set_id;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.register_parent_set_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.register_parent_set_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing register_parent_set_response instance */
    private Builder(avro.java.gpudb.register_parent_set_response other) {
            super(avro.java.gpudb.register_parent_set_response.SCHEMA$);
      if (isValidValue(fields()[0], other.set_id)) {
        this.set_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.set_id);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'set_id' field */
    public java.lang.CharSequence getSetId() {
      return set_id;
    }
    
    /** Sets the value of the 'set_id' field */
    public avro.java.gpudb.register_parent_set_response.Builder setSetId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.set_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'set_id' field has been set */
    public boolean hasSetId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'set_id' field */
    public avro.java.gpudb.register_parent_set_response.Builder clearSetId() {
      set_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public register_parent_set_response build() {
      try {
        register_parent_set_response record = new register_parent_set_response();
        record.set_id = fieldSetFlags()[0] ? this.set_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
