/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class set_info_response extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"set_info_response\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"type_ids\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"set_ids\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"type_schemas\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"labels\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"semantic_types\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"sorted\",\"type\":{\"type\":\"array\",\"items\":\"boolean\"}},{\"name\":\"ttls\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"annotations\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"string\"}}}}]}");
  @Deprecated public java.util.List<java.lang.CharSequence> type_ids;
  @Deprecated public java.util.List<java.lang.CharSequence> set_ids;
  @Deprecated public java.util.List<java.lang.CharSequence> type_schemas;
  @Deprecated public java.util.List<java.lang.CharSequence> labels;
  @Deprecated public java.util.List<java.lang.CharSequence> semantic_types;
  @Deprecated public java.util.List<java.lang.Boolean> sorted;
  @Deprecated public java.util.List<java.lang.Integer> ttls;
  @Deprecated public java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>> annotations;

  /**
   * Default constructor.
   */
  public set_info_response() {}

  /**
   * All-args constructor.
   */
  public set_info_response(java.util.List<java.lang.CharSequence> type_ids, java.util.List<java.lang.CharSequence> set_ids, java.util.List<java.lang.CharSequence> type_schemas, java.util.List<java.lang.CharSequence> labels, java.util.List<java.lang.CharSequence> semantic_types, java.util.List<java.lang.Boolean> sorted, java.util.List<java.lang.Integer> ttls, java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>> annotations) {
    this.type_ids = type_ids;
    this.set_ids = set_ids;
    this.type_schemas = type_schemas;
    this.labels = labels;
    this.semantic_types = semantic_types;
    this.sorted = sorted;
    this.ttls = ttls;
    this.annotations = annotations;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type_ids;
    case 1: return set_ids;
    case 2: return type_schemas;
    case 3: return labels;
    case 4: return semantic_types;
    case 5: return sorted;
    case 6: return ttls;
    case 7: return annotations;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type_ids = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: set_ids = (java.util.List<java.lang.CharSequence>)value$; break;
    case 2: type_schemas = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: labels = (java.util.List<java.lang.CharSequence>)value$; break;
    case 4: semantic_types = (java.util.List<java.lang.CharSequence>)value$; break;
    case 5: sorted = (java.util.List<java.lang.Boolean>)value$; break;
    case 6: ttls = (java.util.List<java.lang.Integer>)value$; break;
    case 7: annotations = (java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type_ids' field.
   */
  public java.util.List<java.lang.CharSequence> getTypeIds() {
    return type_ids;
  }

  /**
   * Sets the value of the 'type_ids' field.
   * @param value the value to set.
   */
  public void setTypeIds(java.util.List<java.lang.CharSequence> value) {
    this.type_ids = value;
  }

  /**
   * Gets the value of the 'set_ids' field.
   */
  public java.util.List<java.lang.CharSequence> getSetIds() {
    return set_ids;
  }

  /**
   * Sets the value of the 'set_ids' field.
   * @param value the value to set.
   */
  public void setSetIds(java.util.List<java.lang.CharSequence> value) {
    this.set_ids = value;
  }

  /**
   * Gets the value of the 'type_schemas' field.
   */
  public java.util.List<java.lang.CharSequence> getTypeSchemas() {
    return type_schemas;
  }

  /**
   * Sets the value of the 'type_schemas' field.
   * @param value the value to set.
   */
  public void setTypeSchemas(java.util.List<java.lang.CharSequence> value) {
    this.type_schemas = value;
  }

  /**
   * Gets the value of the 'labels' field.
   */
  public java.util.List<java.lang.CharSequence> getLabels() {
    return labels;
  }

  /**
   * Sets the value of the 'labels' field.
   * @param value the value to set.
   */
  public void setLabels(java.util.List<java.lang.CharSequence> value) {
    this.labels = value;
  }

  /**
   * Gets the value of the 'semantic_types' field.
   */
  public java.util.List<java.lang.CharSequence> getSemanticTypes() {
    return semantic_types;
  }

  /**
   * Sets the value of the 'semantic_types' field.
   * @param value the value to set.
   */
  public void setSemanticTypes(java.util.List<java.lang.CharSequence> value) {
    this.semantic_types = value;
  }

  /**
   * Gets the value of the 'sorted' field.
   */
  public java.util.List<java.lang.Boolean> getSorted() {
    return sorted;
  }

  /**
   * Sets the value of the 'sorted' field.
   * @param value the value to set.
   */
  public void setSorted(java.util.List<java.lang.Boolean> value) {
    this.sorted = value;
  }

  /**
   * Gets the value of the 'ttls' field.
   */
  public java.util.List<java.lang.Integer> getTtls() {
    return ttls;
  }

  /**
   * Sets the value of the 'ttls' field.
   * @param value the value to set.
   */
  public void setTtls(java.util.List<java.lang.Integer> value) {
    this.ttls = value;
  }

  /**
   * Gets the value of the 'annotations' field.
   */
  public java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>> getAnnotations() {
    return annotations;
  }

  /**
   * Sets the value of the 'annotations' field.
   * @param value the value to set.
   */
  public void setAnnotations(java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>> value) {
    this.annotations = value;
  }

  /** Creates a new set_info_response RecordBuilder */
  public static avro.java.gpudb.set_info_response.Builder newBuilder() {
    return new avro.java.gpudb.set_info_response.Builder();
  }
  
  /** Creates a new set_info_response RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.set_info_response.Builder newBuilder(avro.java.gpudb.set_info_response.Builder other) {
    return new avro.java.gpudb.set_info_response.Builder(other);
  }
  
  /** Creates a new set_info_response RecordBuilder by copying an existing set_info_response instance */
  public static avro.java.gpudb.set_info_response.Builder newBuilder(avro.java.gpudb.set_info_response other) {
    return new avro.java.gpudb.set_info_response.Builder(other);
  }
  
  /**
   * RecordBuilder for set_info_response instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<set_info_response>
    implements org.apache.avro.data.RecordBuilder<set_info_response> {

    private java.util.List<java.lang.CharSequence> type_ids;
    private java.util.List<java.lang.CharSequence> set_ids;
    private java.util.List<java.lang.CharSequence> type_schemas;
    private java.util.List<java.lang.CharSequence> labels;
    private java.util.List<java.lang.CharSequence> semantic_types;
    private java.util.List<java.lang.Boolean> sorted;
    private java.util.List<java.lang.Integer> ttls;
    private java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>> annotations;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.set_info_response.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.set_info_response.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing set_info_response instance */
    private Builder(avro.java.gpudb.set_info_response other) {
            super(avro.java.gpudb.set_info_response.SCHEMA$);
      if (isValidValue(fields()[0], other.type_ids)) {
        this.type_ids = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[0].schema(), other.type_ids);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.set_ids)) {
        this.set_ids = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[1].schema(), other.set_ids);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type_schemas)) {
        this.type_schemas = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[2].schema(), other.type_schemas);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.labels)) {
        this.labels = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[3].schema(), other.labels);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.semantic_types)) {
        this.semantic_types = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[4].schema(), other.semantic_types);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sorted)) {
        this.sorted = (java.util.List<java.lang.Boolean>) data().deepCopy(fields()[5].schema(), other.sorted);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ttls)) {
        this.ttls = (java.util.List<java.lang.Integer>) data().deepCopy(fields()[6].schema(), other.ttls);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.annotations)) {
        this.annotations = (java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>>) data().deepCopy(fields()[7].schema(), other.annotations);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'type_ids' field */
    public java.util.List<java.lang.CharSequence> getTypeIds() {
      return type_ids;
    }
    
    /** Sets the value of the 'type_ids' field */
    public avro.java.gpudb.set_info_response.Builder setTypeIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.type_ids = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'type_ids' field has been set */
    public boolean hasTypeIds() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'type_ids' field */
    public avro.java.gpudb.set_info_response.Builder clearTypeIds() {
      type_ids = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'set_ids' field */
    public java.util.List<java.lang.CharSequence> getSetIds() {
      return set_ids;
    }
    
    /** Sets the value of the 'set_ids' field */
    public avro.java.gpudb.set_info_response.Builder setSetIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.set_ids = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'set_ids' field has been set */
    public boolean hasSetIds() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'set_ids' field */
    public avro.java.gpudb.set_info_response.Builder clearSetIds() {
      set_ids = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'type_schemas' field */
    public java.util.List<java.lang.CharSequence> getTypeSchemas() {
      return type_schemas;
    }
    
    /** Sets the value of the 'type_schemas' field */
    public avro.java.gpudb.set_info_response.Builder setTypeSchemas(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.type_schemas = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'type_schemas' field has been set */
    public boolean hasTypeSchemas() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'type_schemas' field */
    public avro.java.gpudb.set_info_response.Builder clearTypeSchemas() {
      type_schemas = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'labels' field */
    public java.util.List<java.lang.CharSequence> getLabels() {
      return labels;
    }
    
    /** Sets the value of the 'labels' field */
    public avro.java.gpudb.set_info_response.Builder setLabels(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.labels = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'labels' field has been set */
    public boolean hasLabels() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'labels' field */
    public avro.java.gpudb.set_info_response.Builder clearLabels() {
      labels = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'semantic_types' field */
    public java.util.List<java.lang.CharSequence> getSemanticTypes() {
      return semantic_types;
    }
    
    /** Sets the value of the 'semantic_types' field */
    public avro.java.gpudb.set_info_response.Builder setSemanticTypes(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.semantic_types = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'semantic_types' field has been set */
    public boolean hasSemanticTypes() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'semantic_types' field */
    public avro.java.gpudb.set_info_response.Builder clearSemanticTypes() {
      semantic_types = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'sorted' field */
    public java.util.List<java.lang.Boolean> getSorted() {
      return sorted;
    }
    
    /** Sets the value of the 'sorted' field */
    public avro.java.gpudb.set_info_response.Builder setSorted(java.util.List<java.lang.Boolean> value) {
      validate(fields()[5], value);
      this.sorted = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'sorted' field has been set */
    public boolean hasSorted() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'sorted' field */
    public avro.java.gpudb.set_info_response.Builder clearSorted() {
      sorted = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'ttls' field */
    public java.util.List<java.lang.Integer> getTtls() {
      return ttls;
    }
    
    /** Sets the value of the 'ttls' field */
    public avro.java.gpudb.set_info_response.Builder setTtls(java.util.List<java.lang.Integer> value) {
      validate(fields()[6], value);
      this.ttls = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'ttls' field has been set */
    public boolean hasTtls() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'ttls' field */
    public avro.java.gpudb.set_info_response.Builder clearTtls() {
      ttls = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'annotations' field */
    public java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>> getAnnotations() {
      return annotations;
    }
    
    /** Sets the value of the 'annotations' field */
    public avro.java.gpudb.set_info_response.Builder setAnnotations(java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>> value) {
      validate(fields()[7], value);
      this.annotations = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'annotations' field has been set */
    public boolean hasAnnotations() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'annotations' field */
    public avro.java.gpudb.set_info_response.Builder clearAnnotations() {
      annotations = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public set_info_response build() {
      try {
        set_info_response record = new set_info_response();
        record.type_ids = fieldSetFlags()[0] ? this.type_ids : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.set_ids = fieldSetFlags()[1] ? this.set_ids : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        record.type_schemas = fieldSetFlags()[2] ? this.type_schemas : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.labels = fieldSetFlags()[3] ? this.labels : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        record.semantic_types = fieldSetFlags()[4] ? this.semantic_types : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        record.sorted = fieldSetFlags()[5] ? this.sorted : (java.util.List<java.lang.Boolean>) defaultValue(fields()[5]);
        record.ttls = fieldSetFlags()[6] ? this.ttls : (java.util.List<java.lang.Integer>) defaultValue(fields()[6]);
        record.annotations = fieldSetFlags()[7] ? this.annotations : (java.util.List<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>>) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
