/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class trigger_notification extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"trigger_notification\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"trigger_id\",\"type\":\"string\"},{\"name\":\"set_id\",\"type\":\"string\"},{\"name\":\"object_id\",\"type\":\"string\"},{\"name\":\"object_data\",\"type\":\"bytes\"}]}");
  @Deprecated public java.lang.CharSequence trigger_id;
  @Deprecated public java.lang.CharSequence set_id;
  @Deprecated public java.lang.CharSequence object_id;
  @Deprecated public java.nio.ByteBuffer object_data;

  /**
   * Default constructor.
   */
  public trigger_notification() {}

  /**
   * All-args constructor.
   */
  public trigger_notification(java.lang.CharSequence trigger_id, java.lang.CharSequence set_id, java.lang.CharSequence object_id, java.nio.ByteBuffer object_data) {
    this.trigger_id = trigger_id;
    this.set_id = set_id;
    this.object_id = object_id;
    this.object_data = object_data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return trigger_id;
    case 1: return set_id;
    case 2: return object_id;
    case 3: return object_data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: trigger_id = (java.lang.CharSequence)value$; break;
    case 1: set_id = (java.lang.CharSequence)value$; break;
    case 2: object_id = (java.lang.CharSequence)value$; break;
    case 3: object_data = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'trigger_id' field.
   */
  public java.lang.CharSequence getTriggerId() {
    return trigger_id;
  }

  /**
   * Sets the value of the 'trigger_id' field.
   * @param value the value to set.
   */
  public void setTriggerId(java.lang.CharSequence value) {
    this.trigger_id = value;
  }

  /**
   * Gets the value of the 'set_id' field.
   */
  public java.lang.CharSequence getSetId() {
    return set_id;
  }

  /**
   * Sets the value of the 'set_id' field.
   * @param value the value to set.
   */
  public void setSetId(java.lang.CharSequence value) {
    this.set_id = value;
  }

  /**
   * Gets the value of the 'object_id' field.
   */
  public java.lang.CharSequence getObjectId() {
    return object_id;
  }

  /**
   * Sets the value of the 'object_id' field.
   * @param value the value to set.
   */
  public void setObjectId(java.lang.CharSequence value) {
    this.object_id = value;
  }

  /**
   * Gets the value of the 'object_data' field.
   */
  public java.nio.ByteBuffer getObjectData() {
    return object_data;
  }

  /**
   * Sets the value of the 'object_data' field.
   * @param value the value to set.
   */
  public void setObjectData(java.nio.ByteBuffer value) {
    this.object_data = value;
  }

  /** Creates a new trigger_notification RecordBuilder */
  public static avro.java.gpudb.trigger_notification.Builder newBuilder() {
    return new avro.java.gpudb.trigger_notification.Builder();
  }
  
  /** Creates a new trigger_notification RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.trigger_notification.Builder newBuilder(avro.java.gpudb.trigger_notification.Builder other) {
    return new avro.java.gpudb.trigger_notification.Builder(other);
  }
  
  /** Creates a new trigger_notification RecordBuilder by copying an existing trigger_notification instance */
  public static avro.java.gpudb.trigger_notification.Builder newBuilder(avro.java.gpudb.trigger_notification other) {
    return new avro.java.gpudb.trigger_notification.Builder(other);
  }
  
  /**
   * RecordBuilder for trigger_notification instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<trigger_notification>
    implements org.apache.avro.data.RecordBuilder<trigger_notification> {

    private java.lang.CharSequence trigger_id;
    private java.lang.CharSequence set_id;
    private java.lang.CharSequence object_id;
    private java.nio.ByteBuffer object_data;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.trigger_notification.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.trigger_notification.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing trigger_notification instance */
    private Builder(avro.java.gpudb.trigger_notification other) {
            super(avro.java.gpudb.trigger_notification.SCHEMA$);
      if (isValidValue(fields()[0], other.trigger_id)) {
        this.trigger_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.trigger_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.set_id)) {
        this.set_id = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.set_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.object_id)) {
        this.object_id = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.object_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.object_data)) {
        this.object_data = (java.nio.ByteBuffer) data().deepCopy(fields()[3].schema(), other.object_data);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'trigger_id' field */
    public java.lang.CharSequence getTriggerId() {
      return trigger_id;
    }
    
    /** Sets the value of the 'trigger_id' field */
    public avro.java.gpudb.trigger_notification.Builder setTriggerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.trigger_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'trigger_id' field has been set */
    public boolean hasTriggerId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'trigger_id' field */
    public avro.java.gpudb.trigger_notification.Builder clearTriggerId() {
      trigger_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'set_id' field */
    public java.lang.CharSequence getSetId() {
      return set_id;
    }
    
    /** Sets the value of the 'set_id' field */
    public avro.java.gpudb.trigger_notification.Builder setSetId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.set_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'set_id' field has been set */
    public boolean hasSetId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'set_id' field */
    public avro.java.gpudb.trigger_notification.Builder clearSetId() {
      set_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'object_id' field */
    public java.lang.CharSequence getObjectId() {
      return object_id;
    }
    
    /** Sets the value of the 'object_id' field */
    public avro.java.gpudb.trigger_notification.Builder setObjectId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.object_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'object_id' field has been set */
    public boolean hasObjectId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'object_id' field */
    public avro.java.gpudb.trigger_notification.Builder clearObjectId() {
      object_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'object_data' field */
    public java.nio.ByteBuffer getObjectData() {
      return object_data;
    }
    
    /** Sets the value of the 'object_data' field */
    public avro.java.gpudb.trigger_notification.Builder setObjectData(java.nio.ByteBuffer value) {
      validate(fields()[3], value);
      this.object_data = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'object_data' field has been set */
    public boolean hasObjectData() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'object_data' field */
    public avro.java.gpudb.trigger_notification.Builder clearObjectData() {
      object_data = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public trigger_notification build() {
      try {
        trigger_notification record = new trigger_notification();
        record.trigger_id = fieldSetFlags()[0] ? this.trigger_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.set_id = fieldSetFlags()[1] ? this.set_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.object_id = fieldSetFlags()[2] ? this.object_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.object_data = fieldSetFlags()[3] ? this.object_data : (java.nio.ByteBuffer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
