/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.java.gpudb;  
@SuppressWarnings("all")
public class update_set_properties_request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"update_set_properties_request\",\"namespace\":\"avro.java.gpudb\",\"fields\":[{\"name\":\"set_ids\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"properties_map\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}");
  @Deprecated public java.util.List<java.lang.CharSequence> set_ids;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> properties_map;

  /**
   * Default constructor.
   */
  public update_set_properties_request() {}

  /**
   * All-args constructor.
   */
  public update_set_properties_request(java.util.List<java.lang.CharSequence> set_ids, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> properties_map) {
    this.set_ids = set_ids;
    this.properties_map = properties_map;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return set_ids;
    case 1: return properties_map;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: set_ids = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: properties_map = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'set_ids' field.
   */
  public java.util.List<java.lang.CharSequence> getSetIds() {
    return set_ids;
  }

  /**
   * Sets the value of the 'set_ids' field.
   * @param value the value to set.
   */
  public void setSetIds(java.util.List<java.lang.CharSequence> value) {
    this.set_ids = value;
  }

  /**
   * Gets the value of the 'properties_map' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getPropertiesMap() {
    return properties_map;
  }

  /**
   * Sets the value of the 'properties_map' field.
   * @param value the value to set.
   */
  public void setPropertiesMap(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.properties_map = value;
  }

  /** Creates a new update_set_properties_request RecordBuilder */
  public static avro.java.gpudb.update_set_properties_request.Builder newBuilder() {
    return new avro.java.gpudb.update_set_properties_request.Builder();
  }
  
  /** Creates a new update_set_properties_request RecordBuilder by copying an existing Builder */
  public static avro.java.gpudb.update_set_properties_request.Builder newBuilder(avro.java.gpudb.update_set_properties_request.Builder other) {
    return new avro.java.gpudb.update_set_properties_request.Builder(other);
  }
  
  /** Creates a new update_set_properties_request RecordBuilder by copying an existing update_set_properties_request instance */
  public static avro.java.gpudb.update_set_properties_request.Builder newBuilder(avro.java.gpudb.update_set_properties_request other) {
    return new avro.java.gpudb.update_set_properties_request.Builder(other);
  }
  
  /**
   * RecordBuilder for update_set_properties_request instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<update_set_properties_request>
    implements org.apache.avro.data.RecordBuilder<update_set_properties_request> {

    private java.util.List<java.lang.CharSequence> set_ids;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> properties_map;

    /** Creates a new Builder */
    private Builder() {
      super(avro.java.gpudb.update_set_properties_request.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.java.gpudb.update_set_properties_request.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing update_set_properties_request instance */
    private Builder(avro.java.gpudb.update_set_properties_request other) {
            super(avro.java.gpudb.update_set_properties_request.SCHEMA$);
      if (isValidValue(fields()[0], other.set_ids)) {
        this.set_ids = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[0].schema(), other.set_ids);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.properties_map)) {
        this.properties_map = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) data().deepCopy(fields()[1].schema(), other.properties_map);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'set_ids' field */
    public java.util.List<java.lang.CharSequence> getSetIds() {
      return set_ids;
    }
    
    /** Sets the value of the 'set_ids' field */
    public avro.java.gpudb.update_set_properties_request.Builder setSetIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.set_ids = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'set_ids' field has been set */
    public boolean hasSetIds() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'set_ids' field */
    public avro.java.gpudb.update_set_properties_request.Builder clearSetIds() {
      set_ids = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'properties_map' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getPropertiesMap() {
      return properties_map;
    }
    
    /** Sets the value of the 'properties_map' field */
    public avro.java.gpudb.update_set_properties_request.Builder setPropertiesMap(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.properties_map = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'properties_map' field has been set */
    public boolean hasPropertiesMap() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'properties_map' field */
    public avro.java.gpudb.update_set_properties_request.Builder clearPropertiesMap() {
      properties_map = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public update_set_properties_request build() {
      try {
        update_set_properties_request record = new update_set_properties_request();
        record.set_ids = fieldSetFlags()[0] ? this.set_ids : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.properties_map = fieldSetFlags()[1] ? this.properties_map : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
